---
version: "3.8"
services:
  terraboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE}
      DB_PASSWORD: mypassword
      DB_SSLMODE: disable
      TERRABOARD_NO_VERSIONING: true
      TERRABOARD_NO_LOCKS: true
      GODEBUG: netdns=go
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gorm
    volumes:
      - tb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gorm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tb-data: {}
