{{- if .Values.additionalYamlConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraboard.fullname" . }}-configmap
  labels:
    {{- include "terraboard.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.additionalYamlConfig | toYaml | nindent 4 }}
{{- end }}