{{- if .Values.ingress.enabled -}}
{{- $fullName := include "terraboard.fullname" . -}}
{{- $mainPort := .Values.service.port -}}
{{- $swaggerPort := .Values.swagger.service.port -}}
{{- $oauth2ProxyPort := .Values.oauth2Proxy.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "terraboard.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.oauth2Proxy.enabled }}
    # OAuth2 Proxy authentication annotations
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Preferred-Username"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.hosts }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if $.Values.oauth2Proxy.enabled }}
        # OAuth2 Proxy authentication paths
        - path: /oauth2
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-oauth2-proxy
              port:
                number: {{ $oauth2ProxyPort }}
        {{- end }}
        {{- range .mainPaths }}
        - path: {{ . }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $mainPort }}
        {{- end }}
        {{- range .swaggerPaths }}
        - path: {{ . }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}-swagger
              port:
                number: {{ $swaggerPort }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }} 