{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraboard.fullname" . }}-oauth2-proxy
  labels:
    {{- include "terraboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
type: Opaque
data:
  client-id: {{ .Values.oauth2Proxy.config.clientId | b64enc }}
  client-secret: {{ .Values.oauth2Proxy.config.clientSecret | b64enc }}
  cookie-secret: {{ .Values.oauth2Proxy.config.cookieSecret | b64enc }}
{{- end }}