apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraboard.fullname" . }}
  labels:
    {{- include "terraboard.labels" . | nindent 4 }}
stringData:
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}