apiVersion: v2
name: terraboard
home: https://github.com/nkbud/terraboard
version: __VERSION__
appVersion: "__VERSION__"
description: A web interface for Terraform states
keywords:
  - terraform
sources:
  - https://github.com/nkbud/terraboard
maintainers:
  - name: nkbud
    email: nkbud@users.noreply.github.com