name: Helm

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.1'

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Update Chart.yaml with latest tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/__VERSION__/$VERSION/g" helm/Chart.yaml
          sed -i "s/__VERSION__/$VERSION/g" helm/values.yaml

      - name: Package and push Helm chart
        run: |
          helm package helm/
          helm push terraboard-*.tgz oci://ghcr.io/${{ github.repository_owner }}